### PR TITLE
Fix cotisation creation

### LINKED ISSUE #683: Create cotisations is broken
The cotisation creation page (`#/cotisations_management/create/`) errors when you try to create a new cotisation.  It appears that the page is sending the account text rather than the account ID back to the server.  It should be a quick fix.

### PR DESCRIPTION
**Pull request by jniles**
This PR fixes #683.  It cleans up the code slightly, allowing for fewer checks of data-types by enforcing existence and using 1/0 for checkbox true and false values.  The `<select>` statements for accounts have been optimized slightly.

Finally, it fixes a typo that prevented new cotisations from being created.

### CODE REVIEW

File: client/src/partials/cotisation/create/create_cotisation.js [hunk 1]
```diff
@@ -98,29 +95,30 @@ angular.module('bhima.controllers')
...
+        return messenger.danger($translate.instant('COTISATIONS.NOT_EMPTY'));
       }
+
+      // require small abbreviations
+      if (record.abbr.length > 4) {
+        return messenger.danger($translate.instant('COTISATIONS.NOT_SUP4'));
+      }
+      
+      // all checks pass, we are free to post to the server!
+      connect.basicPut('cotisation', [record])
```
Comment (DedrickEnc) [inline client/src/partials/cotisation/create/create_cotisation.js]: Why not use post instead of basicPut?

Comment (jniles) [inline client/src/partials/cotisation/create/create_cotisation.js]: I didn't want to change the code too much; but you are right, post makes sense.  I'm make the changes.

Comment (jniles) [inline client/src/partials/cotisation/create/create_cotisation.js]: Oh yeah.  I remember now.  Remember, `connect.basicPut()` sends a `POST` HTTP request.  I'll update it to `connect.post()`.

**Comment by jniles** [comment]
@dedrickenc, the updates you requested have landed in this branch.  It can be merged anytime.
