### PR TITLE
FIX(exchange rate): rewrite exchange controller

### LINKED ISSUE #588: Exchange rate module does not display date properly
Under set today's exchange rate in the exchange rate module, the date is blank in Firefox and 'mm/dd/yyyy' in chrome (with en_US locate).

The module works fine, but it's confusing to not know what date your are adding for.  Furthermore, the lack of appearance in Firefox is a bug.

### LINKED ISSUE #673: Set Exchange Rate Console Errors
Randomly, setting an exchange rate results in the following console error:
```js
Error: $scope.globalRates is undefined
$scope.submit/<@https://localhost:8080/js/bhima.min.js:3509:1
```

It doesn't seem to happen regularly, and it does not affect the end result (an exchange rate is added), but it should be fixed nonetheless.

### PR DESCRIPTION
**Pull request by jniles**
This commit rewrites the exchange controller.  The following changes
have been introduced:
 1. Simpler date changes and validation in the controller code
 2. Use AngularJS form validation
 3. Dates render properly in the client (fixes #588)
 4. Fixes #673.

### CODE REVIEW

File: client/src/partials/exchange_rate/exchange_rate.js [hunk 1]
```diff
@@ -1,114 +1,125 @@
...
       }
-    };
+    }
+  };
 
-    $scope.maxDate = util.htmlDate(new Date());
-    $scope.currentDate = util.htmlDate(new Date());
-    session.is_oldDate = false;
-    session.oldDate = new Date();
+  //
```
Comment (DedrickEnc) [inline client/src/partials/exchange_rate/exchange_rate.js]: Why not to create a data loader service to load exchange rate for this module? instead of appstate?

Comment (jniles) [inline client/src/partials/exchange_rate/exchange_rate.js]: Your suggestion is essentially #709.  This PR is only a bug fix to address the bugs in #588 and #673.
