### PR TITLE
FIX(login): prevent permissionless login

### LINKED ISSUE #681: Shouldn't be able to login without permissions
You can currently log into bhima even without permissions if your user exists.  This is confusing because the user will not have a tree built (and potentially dangerous since they can still navigate via the URL bar).  We should prevent this by blocking users from logging in if they do not have permissions, potentially with a custom error message.

### PR DESCRIPTION
**Pull request by jniles**
Fixes #681.

This commit adds a check to ensure the user has permissions before login
into bhima. If the user does not have any permissions, we display an error
telling them to contact the system administrator.

**Screenshot** (FR)
permissionlesserror

### CODE REVIEW

File: client/src/partials/auth/login.js [hunk 1]
```diff
@@ -78,7 +78,17 @@ function LoginController($scope, $translate, $location, $http, $timeout, Appcach
       $location.url('/');
     })
     .catch(function (error) {
-      vm.$error = true;
+
+      console.log('The error was:', error);
```
Comment (DedrickEnc) [inline client/src/partials/auth/login.js]: remove this console.log

**Comment by jniles** [comment]
@dedrickenc fixed.
